-- Import Ragno d'Oro Caffe (Giovinazzo) su trovapiatto
-- Eseguire su MySQL: mysql -u USER -p DB_NAME < import-ragno-doro-caffe.sql

START TRANSACTION;

INSERT INTO restaurants (id, name, slug, description, address, phone, email, logo_url, latitude, longitude, city, cuisine, website, rating) VALUES ('rest_ragno_doro_caffe', 'Ragno d\'Oro Caffe', 'ragno-d-oro-caffe', 'Caffè storico dal 1856 nel cuore di Giovinazzo. Bistrot di cucina ricercata con piatti d\'autore, ingredienti selezionati e atmosfera raffinata. Aperto tutti i giorni 8:00-23:30.', 'Piazza Vittorio Emanuele II, 67/68, 70054 Giovinazzo (BA)', NULL, NULL, 'https://www.trovapiatto.it/logo/ragno-doro-caffe.png', 41.1875738, 16.6718963, 'Giovinazzo', 'Bistrot', 'https://ragnodorocaffe.it/bistrot/', NULL);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_ragno_aperitivi', 'rest_ragno_doro_caffe', 'Aperitivi', '', 0);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_001', 'rest_ragno_doro_caffe', 'Aperitivi', 'cat_ragno_aperitivi', 'Ciotola Arachidi e Rice', 'Arachidi e rice soffiato', 2, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_002', 'rest_ragno_doro_caffe', 'Aperitivi', 'cat_ragno_aperitivi', 'Olive, Anacardi e Pistacchi', 'Selezione di olive, anacardi e pistacchi', 2, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_003', 'rest_ragno_doro_caffe', 'Aperitivi', 'cat_ragno_aperitivi', 'Patatine Fox', 'Pepe, aceto, rosmarino, sale, sweet chili. Vegane', 2.5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_004', 'rest_ragno_doro_caffe', 'Aperitivi', 'cat_ragno_aperitivi', 'Ciotola Taralli Artigianali Pugliesi', 'Taralli artigianali pugliesi', 3, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_005', 'rest_ragno_doro_caffe', 'Aperitivi', 'cat_ragno_aperitivi', 'Mandorle Tostate Salate', 'Mandorle tostate salate', 2.5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_006', 'rest_ragno_doro_caffe', 'Aperitivi', 'cat_ragno_aperitivi', 'Tortillas con Salsa Piccante', 'Tortillas con salsa piccante', 3, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_007', 'rest_ragno_doro_caffe', 'Aperitivi', 'cat_ragno_aperitivi', 'Degustazione di Formaggi', 'Degustazione di quattro formaggi dal mondo', 13, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_008', 'rest_ragno_doro_caffe', 'Aperitivi', 'cat_ragno_aperitivi', 'Tramezzo', 'Chiedere al personale l\'assortimento dei gusti', 4.5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_009', 'rest_ragno_doro_caffe', 'Aperitivi', 'cat_ragno_aperitivi', 'Patatine Fritte Dippers', 'Patatine fritte Dippers', 4, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_010', 'rest_ragno_doro_caffe', 'Aperitivi', 'cat_ragno_aperitivi', 'Patatine Fritte Dippers con Fonduta', 'Con fonduta di caciocavallo stagionato in grotta e guanciale croccante', 6.5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_011', 'rest_ragno_doro_caffe', 'Aperitivi', 'cat_ragno_aperitivi', 'Verdure Pastellate', 'Verdure di stagione in pastella croccante', 6, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_012', 'rest_ragno_doro_caffe', 'Aperitivi', 'cat_ragno_aperitivi', 'Prosciutto Crudo Stagionato alla Barese', 'Con olio EVO e pepe Sichuan', 10, true);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_ragno_tapas', 'rest_ragno_doro_caffe', 'Tapas', '', 1);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_013', 'rest_ragno_doro_caffe', 'Tapas', 'cat_ragno_tapas', 'Takobari', 'Takoyaki di pescato, gel di ponzu e mayo alla soia e katsuobushi. 4 pezzi', 12, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_014', 'rest_ragno_doro_caffe', 'Tapas', 'cat_ragno_tapas', 'Il Classico Tonno e Cipolla', 'Gua bao a vapore, brasato di tonno rosso, mayo al lime e crunch di cipolla', 9, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_015', 'rest_ragno_doro_caffe', 'Tapas', 'cat_ragno_tapas', 'Pro-Mex', 'Tacos di frumento, sfilacci di manzo in stile messicano, lattuga, pico de gallo e panna acida', 7, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_016', 'rest_ragno_doro_caffe', 'Tapas', 'cat_ragno_tapas', 'Mini Sando Crab', 'Shokupan, insalata russa di granchio, misticanza di Orto dalla Luna', 10, true);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_ragno_burger-e-panini', 'rest_ragno_doro_caffe', 'Burger e Panini', '', 2);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_017', 'rest_ragno_doro_caffe', 'Burger e Panini', 'cat_ragno_burger-e-panini', 'American Classic Burger', 'Burger 100% Irish Black Angus 200gr, cheddar, cipolla rossa caramellata, guanciale piastrato, lattuga, pomodoro, cetriolo. Con patate Dippers', 13.5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_018', 'rest_ragno_doro_caffe', 'Burger e Panini', 'cat_ragno_burger-e-panini', 'Coleslaw Sandwich', 'Buns, chicken tenders, coleslaw e salsa barbecue homemade', 13.5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_019', 'rest_ragno_doro_caffe', 'Burger e Panini', 'cat_ragno_burger-e-panini', 'Shawrap', 'Wrap, pollo, maiale e agnello marinati, insalata, pomodoro, cipolla caramellata, salsa yogurt', 12, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_020', 'rest_ragno_doro_caffe', 'Burger e Panini', 'cat_ragno_burger-e-panini', 'Alfredo\'s Stick', 'Stick di patata dolce americana in salsa Alfredo', 10, true);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_ragno_starters', 'rest_ragno_doro_caffe', 'Starters', '', 3);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_021', 'rest_ragno_doro_caffe', 'Starters', 'cat_ragno_starters', 'Astice in Campo di Carote', 'Astice al barbecue, carote di Polignano fondenti, mousseline di carote al miso e cialda al sesamo', 28, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_022', 'rest_ragno_doro_caffe', 'Starters', 'cat_ragno_starters', 'Un Uovo Fresco', 'Uovo 68°C, insalatina primavera, mandorla e salsa gribiche', 12, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_023', 'rest_ragno_doro_caffe', 'Starters', 'cat_ragno_starters', 'O\'Toro di Mare', 'Ventresca di tonno al barbecue e gel di daidai ponzu. Gyoza di tonno a vapore, brodo di miso freddo', 21, true);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_ragno_primi-piatti', 'rest_ragno_doro_caffe', 'Primi Piatti', '', 4);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_024', 'rest_ragno_doro_caffe', 'Primi Piatti', 'cat_ragno_primi-piatti', 'Quando un Romano fa la Gricia in Puglia', 'Rigatone Benedetto Cavalieri, fonduta di caciocavallo stagionato in grotta 18 mesi, guanciale Salumificio Pedrazzoli e pepe nero di Sarawak', 14, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_025', 'rest_ragno_doro_caffe', 'Primi Piatti', 'cat_ragno_primi-piatti', 'Gran Cru di Mar', 'Riso carnaroli Meracinque, frutti di mare, burro alle erbe mediterranee', 16, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_026', 'rest_ragno_doro_caffe', 'Primi Piatti', 'cat_ragno_primi-piatti', 'Farciamo un Lento', 'Tortello, pizzaiola di lumache, riduzione di pizzaiola', 14, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_027', 'rest_ragno_doro_caffe', 'Primi Piatti', 'cat_ragno_primi-piatti', 'Ei Fu dei Pescatori', 'Pasta mista Pastai Sanniti, bouillabaisse di pescato, pescato cotto e crudo, mazzancolle e sommacco', 14, true);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_ragno_main-course', 'rest_ragno_doro_caffe', 'Main Course', '', 5);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_028', 'rest_ragno_doro_caffe', 'Main Course', 'cat_ragno_main-course', 'Filetto dei Fondatori', 'Filetto di manzo panato a cappero e pepe, salsa al pepe verde fermentato, demi-glace di manzo, colatura di alici e capperi', 22, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_029', 'rest_ragno_doro_caffe', 'Main Course', 'cat_ragno_main-course', 'Seppia e Agnello', 'Seppia cruda e al barbecue, il suo ragù, ristretto di agnello e mayo sifonata di seppia', 15, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_030', 'rest_ragno_doro_caffe', 'Main Course', 'cat_ragno_main-course', 'Agnello e Seppia', 'Lombo di agnello ripieno di carota, ristretto di seppia e funghi finferli', 19, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_031', 'rest_ragno_doro_caffe', 'Main Course', 'cat_ragno_main-course', 'Un, Due, Tre… Corba!', 'Lombo di corba rossa del Gargano, dashi e olio al finocchietto. Carpaccio in brodo di finocchio e stracotto con pelle croccante', 18, true);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_ragno_insalate', 'rest_ragno_doro_caffe', 'Insalate', '', 6);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_032', 'rest_ragno_doro_caffe', 'Insalate', 'cat_ragno_insalate', 'Insalata Vegetariana', 'Lattuga trocadero, pecorino semi-stagionato, carote, pomodorini e cetrioli in salamoia', 8, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_033', 'rest_ragno_doro_caffe', 'Insalate', 'cat_ragno_insalate', 'Insalata Vegana', 'Lattuga trocadero, pomodoro, carote, rucola, mais, noci e mandorle', 8, true);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_ragno_dessert', 'rest_ragno_doro_caffe', 'Dessert', '', 7);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_034', 'rest_ragno_doro_caffe', 'Dessert', 'cat_ragno_dessert', 'Dolcetto o Bruschetto?', 'Pan brioches tostato al burro, pomodoro semicandito, ricotta di pecora, composta di fragole e sorbetto al basilico', 7, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_035', 'rest_ragno_doro_caffe', 'Dessert', 'cat_ragno_dessert', 'Ragno d\'Oro', 'Mousse allo yogurt, mango e cocco', 8, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_036', 'rest_ragno_doro_caffe', 'Dessert', 'cat_ragno_dessert', 'Susina e Altre Complicazioni', 'Susina, composta e granita, spuma di miele, crumble di fava tonka, amaranto soffiato e polline', 7, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_037', 'rest_ragno_doro_caffe', 'Dessert', 'cat_ragno_dessert', 'Degustazione di Formaggi', 'Degustazione di quattro formaggi dal mondo', 13, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_ragno_038', 'rest_ragno_doro_caffe', 'Dessert', 'cat_ragno_dessert', 'Quartino', 'Quattro gusti a scelta: Classico, Torino, Pianista, Fondatore', 5, true);

COMMIT;
-- Totale: 1 ristorante, 8 categorie, 38 piatti
