-- Import Nicolaus Bistrot - Il Bistrot dal Mare (Bari) su trovapiatto
-- Menu trascritto dal PDF ufficiale (Menu Ita 2025) - Settembre 2026
-- Eseguire su MySQL: mysql -u USER -p DB_NAME < import-nicolaus-bistrot.sql

START TRANSACTION;

INSERT INTO restaurants (id, name, slug, description, address, phone, email, logo_url, latitude, longitude, city, cuisine, website, rating) VALUES ('rest_nicolaus_bistrot', 'Nicolaus Bistrot', 'nicolaus-bistrot', 'Il Bistrot dal Mare nel cuore di Bari: tradizione del pesce barese e cucina moderna, con pescato quotidiano dai pescherecci di famiglia. Antipasti di mare, primi, secondi, panini di pesce e carta dei vini.', 'Corso Vittorio Emanuele II, 37, 70122 Bari', '080 918 4894', NULL, 'https://www.trovapiatto.it/logo/nicolaus-bistrot.png', 41.1264697, 16.8706151, 'Bari', 'Pesce', 'https://nicolausbistrot.it/', NULL);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_nicolaus_antipasti', 'rest_nicolaus_bistrot', 'Antipasti', '', 0);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_001', 'rest_nicolaus_bistrot', 'Antipasti', 'cat_nicolaus_antipasti', 'Crudo Mare alla Barese', 'Crudo di mare alla barese', 12, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_002', 'rest_nicolaus_bistrot', 'Antipasti', 'cat_nicolaus_antipasti', 'Tartare di Tonno o Salmone', 'Tartare di tonno o salmone', 10, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_003', 'rest_nicolaus_bistrot', 'Antipasti', 'cat_nicolaus_antipasti', 'Carpaccio Misto', 'Carpaccio misto di pesce', 7, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_004', 'rest_nicolaus_bistrot', 'Antipasti', 'cat_nicolaus_antipasti', 'Insalata di Mare', 'Insalata di mare', 10, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_005', 'rest_nicolaus_bistrot', 'Antipasti', 'cat_nicolaus_antipasti', 'Gamberi alla Catalana', 'Gamberi alla catalana', 10, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_006', 'rest_nicolaus_bistrot', 'Antipasti', 'cat_nicolaus_antipasti', 'Impepata di Cozze', 'Impepata di cozze', 7, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_007', 'rest_nicolaus_bistrot', 'Antipasti', 'cat_nicolaus_antipasti', 'Cozze Gratinate', 'Cozze gratinate', 7, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_008', 'rest_nicolaus_bistrot', 'Antipasti', 'cat_nicolaus_antipasti', 'Polpette di Pesce in Salsa', 'Polpette di pesce in salsa', 6, true);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_nicolaus_primi', 'rest_nicolaus_bistrot', 'Primi', '', 1);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_009', 'rest_nicolaus_bistrot', 'Primi', 'cat_nicolaus_primi', 'La Tiedd Patate Riso e Cozze', 'Tiella barese: patate, riso e cozze', 8, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_010', 'rest_nicolaus_bistrot', 'Primi', 'cat_nicolaus_primi', 'Cavatello Fresco ai Frutti di Mare', 'Cavatello fresco ai frutti di mare', 10, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_011', 'rest_nicolaus_bistrot', 'Primi', 'cat_nicolaus_primi', 'Spaghettone Aglio Olio e Peperoncino con Tartare di Scampi', 'Spaghettone aglio, olio e peperoncino con tartare di scampi', 14, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_012', 'rest_nicolaus_bistrot', 'Primi', 'cat_nicolaus_primi', 'Tagliolino con Datterino Giallo e Sfilettato di Spigola', 'Tagliolino con datterino giallo e sfilettato di spigola', 15, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_013', 'rest_nicolaus_bistrot', 'Primi', 'cat_nicolaus_primi', 'Spaghettone alle Vongole', 'Spaghettone alle vongole', 14, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_014', 'rest_nicolaus_bistrot', 'Primi', 'cat_nicolaus_primi', 'Spaghettone alle Cozze', 'Spaghettone alle cozze', 10, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_015', 'rest_nicolaus_bistrot', 'Primi', 'cat_nicolaus_primi', 'Risotto Lime Pistacchio e Tartare di Gambero Rosso', 'Risotto lime, pistacchio e tartare di gambero rosso', 15, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_016', 'rest_nicolaus_bistrot', 'Primi', 'cat_nicolaus_primi', 'Tagliolino o Pacchero con Astice', 'Tagliolino o pacchero con astice', 20, true);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_nicolaus_secondi', 'rest_nicolaus_bistrot', 'Secondi', '', 2);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_017', 'rest_nicolaus_bistrot', 'Secondi', 'cat_nicolaus_secondi', 'Frittura Mista di Mare', 'Frittura mista di mare', 10, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_018', 'rest_nicolaus_bistrot', 'Secondi', 'cat_nicolaus_secondi', 'Frittura di Calamari', 'Frittura di calamari', 13, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_019', 'rest_nicolaus_bistrot', 'Secondi', 'cat_nicolaus_secondi', 'Polpo Grigliato', 'Polpo grigliato', 10, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_020', 'rest_nicolaus_bistrot', 'Secondi', 'cat_nicolaus_secondi', 'Polpo Brasato con Crema di Cicerchia', 'Polpo brasato con crema di cicerchia', 10, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_021', 'rest_nicolaus_bistrot', 'Secondi', 'cat_nicolaus_secondi', 'Tonno Scottato', 'Tonno scottato', 14, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_022', 'rest_nicolaus_bistrot', 'Secondi', 'cat_nicolaus_secondi', 'Salmone Arrosto', 'Salmone arrosto', 14, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_023', 'rest_nicolaus_bistrot', 'Secondi', 'cat_nicolaus_secondi', 'Pesce Spada Arrosto', 'Pesce spada arrosto', 14, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_024', 'rest_nicolaus_bistrot', 'Secondi', 'cat_nicolaus_secondi', 'Orata o Spigola al Forno', 'Orata o spigola al forno', 15, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_025', 'rest_nicolaus_bistrot', 'Secondi', 'cat_nicolaus_secondi', 'Pescato del Giorno', 'Pescato del giorno, dai 45 ai 60 euro al kg', 60, true);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_nicolaus_panini', 'rest_nicolaus_bistrot', 'Panini', '', 3);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_026', 'rest_nicolaus_bistrot', 'Panini', 'cat_nicolaus_panini', 'U Forestir', 'Cotoletta di pesce, salsa tartara, bufala affumicata e misticanza', 9, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_027', 'rest_nicolaus_bistrot', 'Panini', 'cat_nicolaus_panini', 'U Tunn', 'Tartare di tonno, pomodoro, olio EVO, stracciatella e granella di pistacchio', 9, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_028', 'rest_nicolaus_bistrot', 'Panini', 'cat_nicolaus_panini', 'U Salmon', 'Carpaccio di salmone marinato, burrata, rucola e salsa guacamole', 9, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_029', 'rest_nicolaus_bistrot', 'Panini', 'cat_nicolaus_panini', 'Sand Nicol', 'Polpo fritto, maionese al lime, misticanza e pomodoro secco', 9, true);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_nicolaus_contorni', 'rest_nicolaus_bistrot', 'Contorni', '', 4);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_030', 'rest_nicolaus_bistrot', 'Contorni', 'cat_nicolaus_contorni', 'Chips', 'Chips', 3, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_031', 'rest_nicolaus_bistrot', 'Contorni', 'cat_nicolaus_contorni', 'Patate al Forno', 'Patate al forno', 5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_032', 'rest_nicolaus_bistrot', 'Contorni', 'cat_nicolaus_contorni', 'Insalata Verde', 'Insalata verde', 5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_033', 'rest_nicolaus_bistrot', 'Contorni', 'cat_nicolaus_contorni', 'Verdure Grigliate', 'Verdure grigliate', 5, true);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_nicolaus_bevande', 'rest_nicolaus_bistrot', 'Bevande', '', 5);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_034', 'rest_nicolaus_bistrot', 'Bevande', 'cat_nicolaus_bevande', 'Acqua Naturale', 'Acqua naturale', 1.5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_035', 'rest_nicolaus_bistrot', 'Bevande', 'cat_nicolaus_bevande', 'Acqua Frizzante', 'Acqua frizzante', 1.5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_036', 'rest_nicolaus_bistrot', 'Bevande', 'cat_nicolaus_bevande', 'Acqua 1L', 'Acqua 1 litro', 2.5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_037', 'rest_nicolaus_bistrot', 'Bevande', 'cat_nicolaus_bevande', 'Coca Cola', 'Coca Cola', 2.5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_038', 'rest_nicolaus_bistrot', 'Bevande', 'cat_nicolaus_bevande', 'Coca Cola Zero', 'Coca Cola Zero', 2.5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_039', 'rest_nicolaus_bistrot', 'Bevande', 'cat_nicolaus_bevande', 'Fanta', 'Fanta', 2.5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_040', 'rest_nicolaus_bistrot', 'Bevande', 'cat_nicolaus_bevande', 'Sprite', 'Sprite', 2.5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_041', 'rest_nicolaus_bistrot', 'Bevande', 'cat_nicolaus_bevande', 'Chino Lurisia', 'Chino Lurisia', 2.5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_042', 'rest_nicolaus_bistrot', 'Bevande', 'cat_nicolaus_bevande', 'Limonata Lurisia', 'Limonata Lurisia', 2.5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_043', 'rest_nicolaus_bistrot', 'Bevande', 'cat_nicolaus_bevande', 'The al Limone', 'The al limone', 2.5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_044', 'rest_nicolaus_bistrot', 'Bevande', 'cat_nicolaus_bevande', 'Peroni Gran Riserva Rossa Bianca 0,50L', 'Peroni Gran Riserva rossa o bianca 0,50 litri', 5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_045', 'rest_nicolaus_bistrot', 'Bevande', 'cat_nicolaus_bevande', 'Peroni Nastro Azzurro alla Spina 0,20L', 'Peroni o Nastro Azzurro alla spina 0,20 litri', 2.5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_046', 'rest_nicolaus_bistrot', 'Bevande', 'cat_nicolaus_bevande', 'Peroni Nastro Azzurro alla Spina 0,40L', 'Peroni o Nastro Azzurro alla spina 0,40 litri', 4.5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_047', 'rest_nicolaus_bistrot', 'Bevande', 'cat_nicolaus_bevande', 'Calice Vino Prosecco', 'Calice vino o prosecco', 3.5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_048', 'rest_nicolaus_bistrot', 'Bevande', 'cat_nicolaus_bevande', 'Aperol Spritz', 'Aperol spritz', 5, true);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_nicolaus_bollicine', 'rest_nicolaus_bistrot', 'Bollicine', '', 6);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_049', 'rest_nicolaus_bistrot', 'Bollicine', 'cat_nicolaus_bollicine', 'Prosecco Millesimato', 'Prosecco spumante DOC extra dry 75cl', 15, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_050', 'rest_nicolaus_bistrot', 'Bollicine', 'cat_nicolaus_bollicine', 'Fratus Bio Brut', 'DOCG Franciacorta 75cl', 30, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_051', 'rest_nicolaus_bistrot', 'Bollicine', 'cat_nicolaus_bollicine', 'Fratus Bio Brut Rose', 'DOCG Franciacorta rose 75cl', 35, true);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_nicolaus_bianchi', 'rest_nicolaus_bistrot', 'Vini Bianchi', '', 7);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_052', 'rest_nicolaus_bistrot', 'Vini Bianchi', 'cat_nicolaus_bianchi', 'Agora Bianco', 'IGT Valle d\u2019Itria 75cl', 16, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_053', 'rest_nicolaus_bistrot', 'Vini Bianchi', 'cat_nicolaus_bianchi', 'Passaturi', 'IGT Valle d\u2019Itria 75cl', 16, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_054', 'rest_nicolaus_bistrot', 'Vini Bianchi', 'cat_nicolaus_bianchi', 'Verdeca', 'IGT Valle d\u2019Itria 75cl', 15, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_055', 'rest_nicolaus_bistrot', 'Vini Bianchi', 'cat_nicolaus_bianchi', 'Bianco d\u2019Alessano', 'Valle d\u2019Itria IGT barricato 75cl', 25, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_056', 'rest_nicolaus_bistrot', 'Vini Bianchi', 'cat_nicolaus_bianchi', 'Chardonnay', 'IGT Salento 75cl', 15, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_057', 'rest_nicolaus_bistrot', 'Vini Bianchi', 'cat_nicolaus_bianchi', 'Vermentino', 'IGP Salento 75cl', 13, true);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_nicolaus_rossi', 'rest_nicolaus_bistrot', 'Vini Rose e Rossi', '', 8);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_058', 'rest_nicolaus_bistrot', 'Vini Rose e Rossi', 'cat_nicolaus_rossi', 'Agora', 'IGT Valle d\u2019Itria rosato 75cl', 16, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_059', 'rest_nicolaus_bistrot', 'Vini Rose e Rossi', 'cat_nicolaus_rossi', 'Tramari', 'IGP Salento rosato 75cl', 18, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_060', 'rest_nicolaus_bistrot', 'Vini Rose e Rossi', 'cat_nicolaus_rossi', 'Murgia Rosa', 'IGT Murgia rosato 75cl', 13, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_061', 'rest_nicolaus_bistrot', 'Vini Rose e Rossi', 'cat_nicolaus_rossi', 'Pungirosa', 'DOCG Castel del Monte rosato 75cl', 16, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_062', 'rest_nicolaus_bistrot', 'Vini Rose e Rossi', 'cat_nicolaus_rossi', 'Calafuria', 'IGT Salento rosato 75cl', 20, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_nicolaus_063', 'rest_nicolaus_bistrot', 'Vini Rose e Rossi', 'cat_nicolaus_rossi', 'Terraria Negroamaro', 'IGT Puglia rosso 75cl', 15, true);

COMMIT;
