-- Import La Muraya Ristorante (Bari) su trovapiatto
-- Menu trascritto dal sito ufficiale lamurayaristorante.com - Settembre 2026
-- Orari: Lun chiuso, Mar-Sab 12:30-15:00 e 19:45-23:00, Dom 12:30-15:00
-- Eseguire su MySQL: mysql -u USER -p DB_NAME < import-la-muraya.sql

START TRANSACTION;

INSERT INTO restaurants (id, name, slug, description, address, phone, email, logo_url, latitude, longitude, city, cuisine, website, rating, available_hours) VALUES ('rest_la_muraya', 'La Muraya Ristorante', 'la-muraya', 'Il miglior ristorante di pesce e non solo a Bari: specialita marinare, ambiente raffinato in Corso Vittorio Emanuele II, sala da 50 coperti e tavoli all\u2019esterno.', 'Corso Vittorio Emanuele II, 140, 70122 Bari', '080 9684581', 'ristorantelamuraya@hotmail.com', 'https://www.trovapiatto.it/logo/la-muraya.png', 41.1256172, 16.8644807, 'Bari', 'Pesce', 'https://lamurayaristorante.com/', NULL, '{"tue":{"lunch":"12:30-15:00","dinner":"19:45-23:00"},"wed":{"lunch":"12:30-15:00","dinner":"19:45-23:00"},"thu":{"lunch":"12:30-15:00","dinner":"19:45-23:00"},"fri":{"lunch":"12:30-15:00","dinner":"19:45-23:00"},"sat":{"lunch":"12:30-15:00","dinner":"19:45-23:00"},"sun":{"lunch":"12:30-15:00"}}');

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_muraya_antipasti', 'rest_la_muraya', 'Antipasti', '', 0);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_001', 'rest_la_muraya', 'Antipasti', 'cat_muraya_antipasti', 'Antipasto di Frutti di Mare Crudi', 'Antipasto di frutti di mare crudi', 18, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_002', 'rest_la_muraya', 'Antipasti', 'cat_muraya_antipasti', 'Carpaccio di Pesce', 'Carpaccio di pesce', 25, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_003', 'rest_la_muraya', 'Antipasti', 'cat_muraya_antipasti', 'Carpaccio di Pesce del Giorno', 'Carpaccio di pesce del giorno, prezzo al kg', 60, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available, image_url) VALUES ('dish_muraya_004', 'rest_la_muraya', 'Antipasti', 'cat_muraya_antipasti', 'Insalata di Mare', 'Insalata di mare', 15, true, 'https://www.trovapiatto.it/images/dishes/muraya-insalata-di-mare.jpg');
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available, image_url) VALUES ('dish_muraya_005', 'rest_la_muraya', 'Antipasti', 'cat_muraya_antipasti', 'Misto Fritto in Tempura', 'Misto fritto in tempura: baccala, caciocavallo, arrosticino di calamaro, gambero', 15, true, 'https://www.trovapiatto.it/images/dishes/muraya-misto-tempura.jpg');
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_006', 'rest_la_muraya', 'Antipasti', 'cat_muraya_antipasti', 'Prosciutto di Parma e Mozzarella', 'Prosciutto di Parma e mozzarella', 15, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_007', 'rest_la_muraya', 'Antipasti', 'cat_muraya_antipasti', 'Tataki di Tonno Rosso al Sesamo', 'Tataki di tonno rosso al sesamo', 18, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_008', 'rest_la_muraya', 'Antipasti', 'cat_muraya_antipasti', 'Tataki al Salmone', 'Tataki al salmone', 18, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available, image_url) VALUES ('dish_muraya_009', 'rest_la_muraya', 'Antipasti', 'cat_muraya_antipasti', 'Capocollo di Martina Franca', 'Capocollo di Martina Franca con pecorino e marmellata', 15, true, 'https://www.trovapiatto.it/images/dishes/muraya-capocollo.jpg');
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available, image_url) VALUES ('dish_muraya_010', 'rest_la_muraya', 'Antipasti', 'cat_muraya_antipasti', 'Insalata di Moscardini', 'Insalata di moscardini, fagiolini, patate alla curcuma e salsa bernese', 15, true, 'https://www.trovapiatto.it/images/dishes/muraya-moscardini.jpg');

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_muraya_primi_mare', 'rest_la_muraya', 'Primi di Mare', '', 1);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_011', 'rest_la_muraya', 'Primi di Mare', 'cat_muraya_primi_mare', 'Agnolotti Neri di Cernia', 'Agnolotti neri ripieni di cernia con crema di limone e gamberi', 18, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_012', 'rest_la_muraya', 'Primi di Mare', 'cat_muraya_primi_mare', 'Mezzemaniche Pescatrice e Gamberi', 'Mezzemaniche con pescatrice, gamberi rossi e pomodorini', 15, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_013', 'rest_la_muraya', 'Primi di Mare', 'cat_muraya_primi_mare', 'Fusilli Pistacchio e Vongole', 'Fusilli avellinesi con pesto di pistacchio e vongole', 15, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_014', 'rest_la_muraya', 'Primi di Mare', 'cat_muraya_primi_mare', 'Spaghetti al Nero di Seppia', 'Spaghetti al nero di seppia con datterino giallo, salicornia e scampi', 18, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_015', 'rest_la_muraya', 'Primi di Mare', 'cat_muraya_primi_mare', 'Spaghetto alla Chitarra Datterino e Gambero', 'Spaghetto alla chitarra, crema di datterino giallo, gambero rosso e sbriciolata di tarallo', 20, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_016', 'rest_la_muraya', 'Primi di Mare', 'cat_muraya_primi_mare', 'Tubettone con Frutti di Mare', 'Tubettone con frutti di mare', 15, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_017', 'rest_la_muraya', 'Primi di Mare', 'cat_muraya_primi_mare', 'Tagliolini Menta e Tartare di Tonno', 'Tagliolini con menta, tartare di tonno rosso e lime', 20, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_018', 'rest_la_muraya', 'Primi di Mare', 'cat_muraya_primi_mare', 'Spaghetto alla Chitarra Ricci e Bottarga', 'Spaghetto alla chitarra con ricci e bottarga', 20, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_019', 'rest_la_muraya', 'Primi di Mare', 'cat_muraya_primi_mare', 'Spaghetto alla Chitarra Cicala o Aragostina', 'Spaghetto alla chitarra con cicala greca o aragostina', 30, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_020', 'rest_la_muraya', 'Primi di Mare', 'cat_muraya_primi_mare', 'Risotto ai Frutti di Mare', 'Risotto ai frutti di mare, minimo 2 porzioni', 15, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_021', 'rest_la_muraya', 'Primi di Mare', 'cat_muraya_primi_mare', 'Risotto Fiori di Zucchina Cozze e Gamberi', 'Risotto con fiori di zucchina, cozze e gamberi, minimo 2 porzioni', 15, true);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_muraya_primi_terra', 'rest_la_muraya', 'Primi di Terra', '', 2);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_022', 'rest_la_muraya', 'Primi di Terra', 'cat_muraya_primi_terra', 'Mezzaluna di Burrata e Pistacchio', 'Mezzaluna ripiena di burrata con pesto di pistacchio e speck', 18, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_023', 'rest_la_muraya', 'Primi di Terra', 'cat_muraya_primi_terra', 'Orecchiette di Grano Arso', 'Orecchiette di grano arso con guanciale, datterino giallo e stracciatella affumicata', 18, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_024', 'rest_la_muraya', 'Primi di Terra', 'cat_muraya_primi_terra', 'Mezzemaniche Fiori di Zucchina e Capocollo', 'Mezzemaniche con fiori di zucchina, capocollo croccante e granella di pistacchio', 15, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_025', 'rest_la_muraya', 'Primi di Terra', 'cat_muraya_primi_terra', 'Spaghetto Cacio Pepe e Capocollo', 'Spaghetto alla chitarra con cacio, pepe e capocollo croccante', 15, true);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_muraya_secondi_pesce', 'rest_la_muraya', 'Secondi di Pesce', '', 3);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_026', 'rest_la_muraya', 'Secondi di Pesce', 'cat_muraya_secondi_pesce', 'Frittura di Calamari e Gamberi', 'Frittura di calamari e gamberi', 12, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_027', 'rest_la_muraya', 'Secondi di Pesce', 'cat_muraya_secondi_pesce', 'Frittura Mista di Pesce', 'Frittura mista: merluzzi, triglie, calamari e gamberi', 15, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_028', 'rest_la_muraya', 'Secondi di Pesce', 'cat_muraya_secondi_pesce', 'Frittura di Paranzella', 'Frittura di paranzella: merluzzi e triglie', 12, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_029', 'rest_la_muraya', 'Secondi di Pesce', 'cat_muraya_secondi_pesce', 'Orata o Spigola alla Griglia', 'Orata o spigola alla griglia (400gr)', 18, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_030', 'rest_la_muraya', 'Secondi di Pesce', 'cat_muraya_secondi_pesce', 'Pescato del Giorno', 'Pesce pescato del giorno: triglie, saraghi, scorfano, rombo. Prezzo al kg', 60, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_031', 'rest_la_muraya', 'Secondi di Pesce', 'cat_muraya_secondi_pesce', 'Scampi alla Griglia', 'Scampi alla griglia', 18, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_032', 'rest_la_muraya', 'Secondi di Pesce', 'cat_muraya_secondi_pesce', 'Gamberoni alla Griglia', 'Gamberoni alla griglia', 15, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_033', 'rest_la_muraya', 'Secondi di Pesce', 'cat_muraya_secondi_pesce', 'Grigliata Mista di Pesce', 'Grigliata mista di pesce: gamberoni, pesce spada, polpo, seppia', 18, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_034', 'rest_la_muraya', 'Secondi di Pesce', 'cat_muraya_secondi_pesce', 'Tagliata di Tonno Rucola e Pomodorini', 'Tagliata di tonno rosso con rucola e pomodorini', 15, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_035', 'rest_la_muraya', 'Secondi di Pesce', 'cat_muraya_secondi_pesce', 'Tagliata di Tonno in Crosta di Pistacchi', 'Tagliata di tonno rosso in crosta di pistacchi e salsa al pecorino', 18, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_036', 'rest_la_muraya', 'Secondi di Pesce', 'cat_muraya_secondi_pesce', 'Pesce Spada alla Brace', 'Pesce spada alla brace o gratinato', 18, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_037', 'rest_la_muraya', 'Secondi di Pesce', 'cat_muraya_secondi_pesce', 'Zuppa di Pesce', 'Zuppa di pesce, 2 porzioni', 50, true);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_muraya_secondi_terra', 'rest_la_muraya', 'Secondi di Terra', '', 4);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_038', 'rest_la_muraya', 'Secondi di Terra', 'cat_muraya_secondi_terra', 'Bistecca di Manzo', 'Bistecca di manzo', 15, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_039', 'rest_la_muraya', 'Secondi di Terra', 'cat_muraya_secondi_terra', 'Tagliata di Manzo', 'Tagliata di manzo con rucola, pomodorini e grana', 15, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_040', 'rest_la_muraya', 'Secondi di Terra', 'cat_muraya_secondi_terra', 'Tagliata di Manzo al Pepe Verde', 'Tagliata di manzo al pepe verde', 18, true);

INSERT INTO categories (id, restaurant_id, name, description, display_order) VALUES ('cat_muraya_dolci', 'rest_la_muraya', 'Frutta e Dolci', '', 5);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_041', 'rest_la_muraya', 'Frutta e Dolci', 'cat_muraya_dolci', 'Frutta di Stagione', 'Frutta di stagione', 4, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_042', 'rest_la_muraya', 'Frutta e Dolci', 'cat_muraya_dolci', 'Sporcamuss', 'Sporcamuss, tipico dolce barese', 4, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_043', 'rest_la_muraya', 'Frutta e Dolci', 'cat_muraya_dolci', 'Souffle al Cioccolato', 'Souffle al cioccolato', 5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_044', 'rest_la_muraya', 'Frutta e Dolci', 'cat_muraya_dolci', 'Crostata Ricotta e Cioccolata', 'Crostata con ricotta e cioccolata', 4, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_045', 'rest_la_muraya', 'Frutta e Dolci', 'cat_muraya_dolci', 'Cassata di Tommasino', 'Cassata di Tommasino: ricotta e pistacchio o torroncino', 5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_046', 'rest_la_muraya', 'Frutta e Dolci', 'cat_muraya_dolci', 'Tartufo di Pizzo', 'Tartufo di Pizzo calabro nero o bianco', 5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_047', 'rest_la_muraya', 'Frutta e Dolci', 'cat_muraya_dolci', 'Cannolo alle Mandorle', 'Cannolo croccante alle mandorle con creme assortite, 2 pezzi', 4, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_048', 'rest_la_muraya', 'Frutta e Dolci', 'cat_muraya_dolci', 'Cheesecake Cioccolato', 'Cheesecake al cioccolato o yogurt e frutti di bosco', 5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_049', 'rest_la_muraya', 'Frutta e Dolci', 'cat_muraya_dolci', 'Cheesecake Yogurt e Frutti di Bosco', 'Cheesecake yogurt e frutti di bosco', 5, true);
INSERT INTO dishes (id, restaurant_id, category, category_id, name, description, price, available) VALUES ('dish_muraya_050', 'rest_la_muraya', 'Frutta e Dolci', 'cat_muraya_dolci', 'Tiramisu', 'Tiramisu', 5, true);

COMMIT;
